"""URIv1 turn layer: contracts and the Semantic Decoder provider slot."""

from uri_v1.turn.contracts import (
    AmbiguityKind,
    AttachmentReference,
    ConfidenceLevel,
    ConstraintScope,
    ContextDependency,
    ContextDependencyCategory,
    ContextPack,
    DecodedRequest,
    EdgeOutcome,
    EntityCategory,
    FinalizedTurn,
    IntendedOutcome,
    IntelligenceResult,
    IntentFamily,
    MentionedEntity,
    OperationStatus,
    OutputPreferences,
    ReferenceKind,
    SemanticAmbiguity,
    SemanticConfidence,
    SemanticOperation,
    SemanticReference,
    TemporalReference,
)
from uri_v1.turn.decoder import DecodeInput, SemanticDecoder
from uri_v1.turn.needle_decoder import (
    NeedleBridgeTransport,
    NeedleDecodeResult,
    NeedleSemanticDecoder,
    NeedleTransportError,
    default_venv_python,
)
from uri_v1.turn.needle_wire import DecodeError, DecodeErrorReason
from uri_v1.turn.needle_narrow import (
    SCHEMA_GOAL,
    SCHEMA_OPERATIONS,
    SCHEMA_REFERENCES,
    SCHEMA_CONSTRAINTS,
    SYSTEM_GOAL,
    SYSTEM_OPERATIONS,
    SYSTEM_REFERENCES,
    SYSTEM_CONSTRAINTS,
    NarrowGoalResult,
    NarrowOperationsResult,
    NarrowReferencesResult,
    NarrowConstraintsResult,
    NeedleNarrowSemanticExtractor,
    normalize_goal,
    normalize_operations,
    normalize_references,
    normalize_constraints,
)
from uri_v1.turn.needle_merge import merge_narrow_results
from uri_v1.turn.qwen_wire import (
    QWEN_SYSTEM_PROMPT,
    QWEN_WIRE_SCHEMA,
    QWEN_WIRE_SCHEMA_NAME,
    normalize_qwen_wire,
    parse_wire_json,
)
from uri_v1.turn.qwen_decoder import (
    QwenDecodeResult,
    QwenLocalTransport,
    QwenSemanticDecoder,
    QwenTransportError,
)
from uri_v1.turn.turn_frame import CandidateAction, CandidateReference, TurnFrame
from uri_v1.turn.turn_frame_builder import build_turn_frame
from uri_v1.turn.active_context import ActiveContext, ArtifactDescriptor, EntityDescriptor
from uri_v1.turn.semantic_envelope import (
    GoalView,
    OperationView,
    OutputScopeView,
    ReferenceView,
    SemanticInputEnvelope,
)
from uri_v1.turn.needle_scaffolded import (
    ScaffoldedNeedleDecoder,
    ScaffoldedNeedleResult,
)
from uri_v1.turn.local_semantic_wire import (
    QWEN14B_WIRE_SCHEMA,
    QWEN14B_WIRE_SCHEMA_NAME,
    SYSTEM_PROMPT_MODE_A,
    SYSTEM_PROMPT_MODE_B,
    SYSTEM_PROMPT_MODE_C,
    SYSTEM_PROMPT_MODE_D,
    format_mode_a_prompt,
    format_mode_b_prompt,
    format_mode_c_prompt,
    format_mode_d_prompt,
    normalize_qwen14b_wire,
)
from uri_v1.turn.qwen_semantic_decoder import (
    DecoderMode,
    Qwen14BDecodeResult,
    Qwen14BSemanticDecoder,
)
from uri_v1.turn.needle_single_pass import (
    NEEDLE_TOOL_SCHEMA,
    NeedleSinglePassDecoder,
    NeedleSinglePassResult,
)
from uri_v1.turn.rar_contracts import (
    RARBasis,
    RARCandidate,
    RARContractViolationError,
    RARDeterministicAnchor,
    RAREvidence,
    RARFailureClass,
    RARFixture,
    RARDriverRule,
    RAROutcome,
    RARQuery,
    RARResolution,
    resolve_rar_deterministically,
    validate_rar_resolution,
)
from uri_v1.turn.rar_deterministic import (
    DeterministicRARTrace,
    classify_unresolved_failure,
    clean_tokens,
    compute_term_document_frequency,
    resolve_rar_deterministic_extended,
    score_candidate_relevance,
    stem_title,
)
from uri_v1.turn.rar_challenge_fixtures import get_rar_challenge_fixtures
from uri_v1.turn.rar_fixtures import get_rar_diagnostic_fixtures

__all__ = [
    # Enums
    "AmbiguityKind",
    "ConfidenceLevel",
    "ContextDependencyCategory",
    "EntityCategory",
    "IntentFamily",
    "OperationStatus",
    "ReferenceKind",
    # Value Objects
    "AttachmentReference",
    "ConstraintScope",
    "ContextDependency",
    "IntendedOutcome",
    "MentionedEntity",
    "OutputPreferences",
    "SemanticAmbiguity",
    "SemanticConfidence",
    "SemanticOperation",
    "SemanticReference",
    "TemporalReference",
    # Pipeline Contracts
    "ContextPack",
    "DecodedRequest",
    "EdgeOutcome",
    "FinalizedTurn",
    "IntelligenceResult",
    # Decoder Interface
    "DecodeInput",
    "SemanticDecoder",
    # Needle 3 implementation (Batch A2)
    "DecodeError",
    "DecodeErrorReason",
    "NeedleBridgeTransport",
    "NeedleDecodeResult",
    "NeedleSemanticDecoder",
    "NeedleTransportError",
    "default_venv_python",
    # Needle 3 Narrow Schemas (Batch A2.1)
    "SCHEMA_GOAL",
    "SCHEMA_OPERATIONS",
    "SCHEMA_REFERENCES",
    "SCHEMA_CONSTRAINTS",
    "SYSTEM_GOAL",
    "SYSTEM_OPERATIONS",
    "SYSTEM_REFERENCES",
    "SYSTEM_CONSTRAINTS",
    "NarrowGoalResult",
    "NarrowOperationsResult",
    "NarrowReferencesResult",
    "NarrowConstraintsResult",
    "NeedleNarrowSemanticExtractor",
    "normalize_goal",
    "normalize_operations",
    "normalize_references",
    "merge_narrow_results",
    # Qwen Candidate (Batch A2.2)
    "QwenLocalTransport",
    "QwenSemanticDecoder",
    "QwenDecodeResult",
    "QwenTransportError",
    "QWEN_WIRE_SCHEMA",
    "QWEN_WIRE_SCHEMA_NAME",
    "QWEN_SYSTEM_PROMPT",
    "normalize_qwen_wire",
    "parse_wire_json",
    # TurnFrame & Scaffolded Needle (Batch A2.3)
    "CandidateAction",
    "CandidateReference",
    "TurnFrame",
    "build_turn_frame",
    "ActiveContext",
    "ArtifactDescriptor",
    "EntityDescriptor",
    "GoalView",
    "OperationView",
    "ReferenceView",
    "OutputScopeView",
    "SemanticInputEnvelope",
    "ScaffoldedNeedleDecoder",
    "ScaffoldedNeedleResult",
    # Qwen3-14B Harness Control (Batch A2.4)
    "DecoderMode",
    "Qwen14BDecodeResult",
    "Qwen14BSemanticDecoder",
    "QWEN14B_WIRE_SCHEMA",
    "QWEN14B_WIRE_SCHEMA_NAME",
    "SYSTEM_PROMPT_MODE_A",
    "SYSTEM_PROMPT_MODE_B",
    "SYSTEM_PROMPT_MODE_C",
    "SYSTEM_PROMPT_MODE_D",
    "format_mode_a_prompt",
    "format_mode_b_prompt",
    "format_mode_c_prompt",
    "format_mode_d_prompt",
    "normalize_qwen14b_wire",
    # Needle Single-Pass Control (Batch A2.4R)
    "NEEDLE_TOOL_SCHEMA",
    "NeedleSinglePassDecoder",
    "NeedleSinglePassResult",
    # Reference Anchor Resolution (Batch A2.5)
    "RARBasis",
    "RARCandidate",
    "RARContractViolationError",
    "RARDeterministicAnchor",
    "RAREvidence",
    "RARFailureClass",
    "RARFixture",
    "RARDriverRule",
    "RAROutcome",
    "RARQuery",
    "RARResolution",
    "get_rar_challenge_fixtures",
    "get_rar_diagnostic_fixtures",
    "resolve_rar_deterministically",
    "validate_rar_resolution",
    # Stage 2 Extended Deterministic Stack
    "DeterministicRARTrace",
    "classify_unresolved_failure",
    "clean_tokens",
    "compute_term_document_frequency",
    "resolve_rar_deterministic_extended",
    "score_candidate_relevance",
    "stem_title",
]
